### ISSUE TITLE
class.Shop.php on line 690

### ISSUE THREAD

**Issue by theemack** [flaneurette/TinyShop#2]
There is an install error that keeps appearing, any idea what it might be?. Version 3.7 installed perfectly without any issues thought i'd try the  fresh version 3. regardless of which php version it brings this error up.

Fatal error: Uncaught Error: Cannot access empty property in /home/test/public_html/shopee/resources/php/class.Shop.php:690 Stack trace: #0 /home/test/public_html/shopee/index.php(60): Shop->getproducts('list', 'index', false, false, false, '32ec9cc18db89e6...') #1 {main} thrown in /home/test/public_html/shopee/resources/php/class.Shop.php on line 690

**Comment by flaneurette** [comment]
Is it version 3.0? latest version is 3.9

**Comment by flaneurette** [comment]
Fixed the bug and published a new release: v3.93

Some versions of PHP handled variables differently. Also optimized it for PHP 8. Minimum requirements is now set to 5.6+
